-- Phase 2.3 — SQL Server DDL bootstrap
-- Source: source-app/backend/app/models/*.py
-- Mapping: docs/25_SQL_Server_Type_Mapping.md
-- FKs deferred to Phase 2.4; indexes deferred to Phase 2.5
-- Table count target: 46 (no customers/sales tables)
--
-- Note: do NOT `USE [dbo]` — dbo is a schema, not a database.
-- Connect to WarehouseErp (or target DB) via sqlcmd -d / SSMS context.